// Generated by https://quicktype.io

export interface NasaPicture {
  date: Date;
  explanation: string;
  hdurl: string;
  media_type: MediaType;
  service_version: ServiceVersion;
  title: string;
  url: string;
  copyright?: string;
}

export enum MediaType {
  Image = 'image',
}

export enum ServiceVersion {
  V1 = 'v1',
}
