// Generated by https://quicktype.io

export interface NasaImage {
  collection: NasaImageCollection;
}

export interface NasaImageCollection {
  href: string;
  items: NasaImageItem[];
  links: NasaImageCollectionLink[];
  metadata: NasaImageMetadata;
  version: string;
}

export interface NasaImageItem {
  data: NasaImageDatum[];
  href: string;
  links: NasaImageItemLink[];
}

export interface NasaImageDatum {
  center: string;
  date_created: Date;
  description: string;
  keywords: string[];
  media_type: string;
  nasa_id: string;
  title: string;
}

export interface NasaImageItemLink {
  href: string;
  rel: string;
  render: string;
}

export interface NasaImageCollectionLink {
  href: string;
  prompt: string;
  rel: string;
}

export interface NasaImageMetadata {
  total_hits: number;
}
